export const initialTopics = [
  {
    id: "lucas-profile",
    parentId: null,
    title: "Lucas Chavez",
    preview: "Junior AI Web Developer candidate based in Australia.",
    note: "Email: LUCK9217@gmail.com | Phone: +61 467520280 | LinkedIn: https://www.linkedin.com/in/lucas-chavez/",
    dueDate: "",
    status: "Active",
    position: { x: 10, y: 12, angle: -2 },
    checklist: [
      { id: "profile-1", text: "Australian work authorization", done: false },
      {
        id: "profile-2",
        text: "Open to 6-month contract to full-time path",
        done: false,
      },
      {
        id: "profile-3",
        text: "Ready to collaborate with lead developer",
        done: false,
      },
    ],
  },
  {
    id: "professional-summary",
    parentId: "lucas-profile",
    title: "Professional summary",
    preview: "Adaptable and passionate software developer.",
    note: "Hands-on experience in web and mobile development, responsive UI delivery, GitHub workflows, and team collaboration.",
    dueDate: "",
    status: "In review",
    checklist: [
      {
        id: "summary-1",
        text: "Strong core programming fundamentals",
        done: false,
      },
      { id: "summary-2", text: "Eager to learn and contribute", done: false },
    ],
  },
  {
    id: "experience",
    parentId: null,
    title: "Experience",
    preview: "Frontend internships and prior reporting automation role.",
    note: "Practical delivery in React, Next.js, Flutter, Firebase, WordPress, and GitHub project workflows.",
    dueDate: "",
    status: "Active",
    position: { x: 39, y: 24, angle: 1 },
    checklist: [
      {
        id: "exp-1",
        text: "SoftLabs internship (Jul 2025 - Oct 2025)",
        done: false,
      },
      {
        id: "exp-2",
        text: "Job Search Ninja internship (Jun 2023 - Dec 2023)",
        done: false,
      },
      {
        id: "exp-3",
        text: "TELECOM S.A SSRS Developer (May 2019 - Mar 2021)",
        done: false,
      },
    ],
  },
  {
    id: "exp-softlabs",
    parentId: "experience",
    title: "SoftLabs",
    preview: "Frontend Developer Intern - Australia.",
    note: "Maintained WordPress/Elementor sites, optimized performance, built responsive UI with HTML/CSS/JavaScript, contributed to React and Next.js pages, and used GitHub Projects.",
    dueDate: "",
    status: "Active",
    checklist: [
      {
        id: "soft-1",
        text: "Bug fixing and performance improvements",
        done: false,
      },
      {
        id: "soft-2",
        text: "Mobile-first UI and cross-browser testing",
        done: false,
      },
    ],
  },
  {
    id: "exp-jsn",
    parentId: "experience",
    title: "Job Search Ninja",
    preview: "Frontend Developer Intern - Australia.",
    note: "Built responsive interfaces in React and Flutter, integrated Firebase realtime features, and collaborated remotely with milestone tracking in GitHub Projects.",
    dueDate: "",
    status: "Steady",
    checklist: [
      { id: "jsn-1", text: "Firebase realtime integration", done: false },
      { id: "jsn-2", text: "Remote team collaboration", done: false },
    ],
  },
  {
    id: "exp-telecom",
    parentId: "experience",
    title: "TELECOM S.A",
    preview: "SSRS Developer - Argentina.",
    note: "Developed internal reporting tools with Visual Basic, SQL, and SAS Guide. Built Node.js automation for document downloads and supported analysis workflows with Excel.",
    dueDate: "",
    status: "In review",
    checklist: [
      { id: "tele-1", text: "Reporting tool development", done: false },
      { id: "tele-2", text: "Node.js automation module", done: false },
    ],
  },
  {
    id: "education",
    parentId: null,
    title: "Education",
    preview: "Formal studies in IT networking and website development.",
    note: "Advanced Diploma of IT (Telecommunications Network Engineering), Diploma of IT (Website Development), Backend/Frontend Bootcamp, and Electronic Technician background.",
    dueDate: "",
    status: "On horizon",
    position: { x: 67, y: 16, angle: -1 },
    checklist: [
      {
        id: "edu-1",
        text: "Advanced Diploma of IT expected 2027",
        done: false,
      },
      { id: "edu-2", text: "Diploma of IT completed Dec 2025", done: false },
      { id: "edu-3", text: "UBA IALAB Bootcamp completed 2022", done: false },
    ],
  },
  {
    id: "edu-advanced-diploma",
    parentId: "education",
    title: "Advanced Diploma of IT",
    preview: "National Institute of Technology, Perth.",
    note: "Expected 2027. Focus areas include WAN design, ICT architecture, advanced IP troubleshooting, project scope planning, and cybersecurity practices.",
    dueDate: "2027-12-01",
    status: "On horizon",
    checklist: [
      { id: "ad-1", text: "Telecommunications network planning", done: false },
      { id: "ad-2", text: "Traffic management and security", done: false },
    ],
  },
  {
    id: "edu-diploma-web",
    parentId: "education",
    title: "Diploma of IT (Web)",
    preview: "Australian College of Business Intelligence, Sydney.",
    note: "Completed Dec 2025. Full-stack development, UX/UI, mobile app development, cybersecurity, and database integration projects.",
    dueDate: "2025-12-01",
    status: "Steady",
    checklist: [
      { id: "dw-1", text: "Full-stack and UX/UI projects", done: false },
      { id: "dw-2", text: "Database integration practice", done: false },
    ],
  },
  {
    id: "skills",
    parentId: null,
    title: "Technical skills",
    preview: "Frontend, backend, database, and delivery toolchain.",
    note: "Languages: JavaScript, TypeScript, Dart, HTML, CSS, SQL, Visual Basic. Frameworks and tools: React, Next.js, Redux, Node.js, GraphQL, Firebase, Flutter.",
    dueDate: "",
    status: "Active",
    position: { x: 18, y: 56, angle: 2 },
    checklist: [
      {
        id: "skill-1",
        text: "Databases: PostgreSQL, Firebase Realtime DB, MongoDB",
        done: false,
      },
      {
        id: "skill-2",
        text: "Tools: Git, GitHub, Kanban, SAS Guide, Excel",
        done: false,
      },
      {
        id: "skill-3",
        text: "Other: UX/UI Design and Agile/Scrum",
        done: false,
      },
    ],
  },
  {
    id: "certifications",
    parentId: "skills",
    title: "Certifications",
    preview: "Linux, Cyber Security, Cloud, and Scrum Foundation.",
    note: "Introduction to Linux (Oct 2025), Introduction to Cyber Security (Nov 2025), Introduction to Cloud Computing (Jun 2025), Scrum Foundation Professional Certificate (Jul 2020 - Current).",
    dueDate: "",
    status: "Active",
    checklist: [
      { id: "cert-1", text: "Linux microskill completed", done: false },
      { id: "cert-2", text: "Cyber Security microskill completed", done: false },
      {
        id: "cert-3",
        text: "Cloud Computing microskill completed",
        done: false,
      },
    ],
  },
  {
    id: "portfolio",
    parentId: null,
    title: "Portfolio and projects",
    preview: "Public repositories and practical builds for recruiters.",
    note: "Main repository: https://github.com/luck9217/brainstorm | Additional project: https://github.com/luck9217/Library_Management_Backend",
    dueDate: "",
    status: "Steady",
    position: { x: 58, y: 60, angle: -3 },
    checklist: [
      {
        id: "port-1",
        text: "Brainstorm Space (Next.js) repo available",
        done: false,
      },
      {
        id: "port-2",
        text: "Library Management Backend repo available",
        done: false,
      },
      { id: "port-3", text: "LinkedIn profile ready", done: false },
    ],
  },
  {
    id: "languages",
    parentId: "skills",
    title: "Languages",
    preview: "English and Spanish.",
    note: "Comfortable collaborating in both English and Spanish.",
    dueDate: "",
    status: "Steady",
    checklist: [
      { id: "lang-1", text: "English", done: false },
      { id: "lang-2", text: "Spanish", done: false },
    ],
  },
];

